### ISSUE TITLE
Creating json response is failing

### ISSUE THREAD

**Issue by mifricke** [B-urb/doclytics#73]
Hi!

I get this error message every time I start the container. Unfortunately, the version in the first line does not match the image used. 
Currently bjoern5urban/doclytics:v1.2.0 is used.

The problem apparently occurs with the ASN. 
Any ideas?

Jul 27 09:54:24.649 INFO Application started, version: 1.1.4-rc.9
Jul 27 09:54:24.744 INFO Fetching custom fields from paperless at http://10.0.1.205:8010
Jul 27 09:54:24.744 DEBG starting new connection: http://10.0.1.205:8010/
Jul 27 09:54:24.782 INFO Fields: [Field { id: 2, name: "tagged", data_type: "boolean" }, Field { id: 1, name: "Person", data_type: "documentlink" }]
Jul 27 09:54:24.782 INFO Retrieve Documents from paperless at: http://10.0.1.205:8010, with query: NOT tagged=true
Jul 27 09:54:30.563 ERRO Error while creating json of document response from paperless invalid type: integer `27`, expected a string at line 1 column 42073
Jul 27 09:54:30.563 ERRO Error at column 42073: ull,"archive_serial_number":27,"original_file_name":"OCR_Sca
Jul 27 09:54:30.563 ERRO Error while interacting with paperless: invalid type: integer `27`, expected a string at line 1 column 42073

**Comment by B-urb** [comment]
Hi, thanks for reporting this issue. It seems that archive serial number has the wrong type in the data model at the moment. Possibly it changed in the paperless spec. I pushed a fix, that is included in v1.2.1-rc.8 that hopefully fixes this. Can you try that image and see if it works ?

**Comment by mifricke** [comment]
Thank you very much! That seems to work. I still have a small problem with Ollama, but I'll get that sorted out ;-)
